account/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', views.StartPageView.as_view(), name='start_page'),
    # auth and reg
    path('register-customer/', views.RegisterCustomerView.as_view(), name='register_customer_page'),
    path('register-station/', views.RegisterStationView.as_view(), name='register_station_page'),
    path('accounts/login/', views.UserLoginView.as_view(), name='login_page'),
    path('accounts/logout/', views.UserLogoutView.as_view(), name='logout_page'),
    path('password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.UserPasswordResetDone.as_view(), name='password_reset_done'),
    re_path(
        r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        views.UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # # customer
    path('customer/<slug:slug>/', views.DetailCustomerView.as_view(), name='detail_customer_page'),
    path('your-dashboard/', views.DashboardCustomerView.as_view(), name='dashboard_customer_page'),
]

adproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.validators import RegexValidator
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext as _
from django.core.validators import FileExtensionValidator

import datetime

from .managers import UserManager
from custom.extra import validate_file_size


# for localization
W_FIRST_NAME = 'first name'
W_LAST_NAME = 'last name'
W_EMAIL_ADDRESS = 'email address'
W_PHONE_NUMBER = 'phone number'
W_TITUL = 'titul'
W_CITY = 'City'
W_STREET = 'Street and number of your building'
W_ADDRESS_CODE = 'Address code'

W_NAME_OF_STATION = 'Name of the station'
W_NAME_OF_COMPANY = 'Name of the company'
W_NUMBER_OF_BUILDING = 'Number of the building'


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.author.username, filename)


def station_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.username, filename)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_('username'), max_length=255, unique=True)
    first_name = models.CharField(_(W_FIRST_NAME), max_length=255)
    last_name = models.CharField(_(W_LAST_NAME), max_length=255)
    email = models.EmailField(_(W_EMAIL_ADDRESS), null=True, blank=True)
    phone_regex = RegexValidator(
        regex=r'^\+?(\d){6,18}$',
        message="Phone number must be entered in the format: '+431234567890' or 01234567890"
    )
    phone = models.CharField(_(W_PHONE_NUMBER), null=True, blank=True, validators=[phone_regex], max_length=17)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=False)
    is_staff = models.BooleanField(_('staff'), default=False)
    is_verified = models.BooleanField(_('verified'), default=False)
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='default_user',
        blank=True
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='default_permission',
        blank=True
    )
    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        unique_together = ('email', 'phone')


class Customer(User, models.Model):
    """The customer"""
    titul_choice = [
        ('Herr', 'Herr'),
        ('Frau', 'Frau'),
        ('Fräulein', 'Fräulein'),
        ('Professor', 'Professor'),
        ('PD', 'PD'),
        ('Doktor', 'Doktor'),
        ('Magister', 'Magister'),
        ('Ingenieur', 'Ingenieur'),
    ]
    user_rate = models.FloatField('Rate', null=True, blank=True)
    total_rate = models.IntegerField('SUM rate', null=True, blank=True)
    rate_number = models.IntegerField('Rate number', null=True, blank=True)
    titul = models.CharField(W_TITUL, max_length=50, null=True, blank=True, choices=titul_choice)
    city = models.CharField(W_CITY, max_length=100)
    street = models.CharField(W_STREET, max_length=100, null=True, blank=True)
    address_code = models.IntegerField(W_ADDRESS_CODE, null=True, blank=True)
    slug = models.SlugField('slug', unique=True)
    create_date = models.DateTimeField('Date of registration', auto_now_add=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'


class Station(User, models.Model):
    """The service station"""
    titul_choice = [
        ('Herr', 'Herr'),
        ('Frau', 'Frau'),
        ('Fräulein', 'Fräulein'),
        ('Professor', 'Professor'),
        ('PD', 'PD'),
        ('Doktor', 'Doktor'),
        ('Magister', 'Magister'),
        ('Ingenieur', 'Ingenieur'),
    ]
    titul = models.CharField(W_TITUL, max_length=50, null=True, blank=True, choices=titul_choice)
    station_rate = models.FloatField('Rate', null=True, blank=True)
    name_stat = models.CharField(W_NAME_OF_STATION, max_length=100)
    name_comp = models.CharField(W_NAME_OF_COMPANY, max_length=100)
    city = models.CharField(W_CITY, max_length=100)
    street = models.CharField(W_STREET, max_length=100)
    house = models.CharField('Number of the building', max_length=100)
    address_code = models.IntegerField(W_ADDRESS_CODE)
    web_site = models.CharField('Web site', max_length=100, null=True, blank=True)
    file_atu = models.FileField('Upload your ATU', upload_to=station_directory_path, null=True, blank=True,
                                validators=[FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']),
                                            validate_file_size]
                                )
    uid = models.CharField('UID', max_length=50)
    cash = models.BooleanField('Cash', default=False)
    card = models.BooleanField('Card', default=False)
    transfer = models.BooleanField('Bank transfer', default=False)
    slug = models.SlugField('slug', unique=True)
    create_date = models.DateTimeField('Date of registration', auto_now_add=True)
    district_choice = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
    ]
    district = models.CharField(
        max_length=30,
        verbose_name='District',
        choices=district_choice,
    )
    middle_rate = models.FloatField('Middle rate', null=True, blank=True)
    total_rate = models.IntegerField('SUM rate', null=True, blank=True)
    offer_number = models.IntegerField('Confirm offer number', default=0)

    def __str__(self):
        return '%s - %s' % (self.name_stat, self.city)

    class Meta:
        verbose_name = 'Service station'
        verbose_name_plural = 'Service stations'

account/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse, reverse_lazy, NoReverseMatch
from django.contrib import messages

from custom.repeated_data import current_data, customer_data, reset_password_words
from account.models import User
from .forms import *


#localization
W_MESSAGE_CREATE_USER = 'The user is created successfully'


class CustomSuccessMessageMixin:
    """The class for displaying a message when working with the form.
    The inherited classes receive the variable success_msg, and a message is passed in it"""
    @property
    def success_msg(self):
        return False

    def error_msg(self):
        return False

    def form_valid(self, form):
        messages.success(self.request, self.success_msg, self.error_msg)
        return super().form_valid(form)


class StartPageView(TemplateView):
    template_name = 'start_page.html'

    def get_context_data(self, **kwargs):
        kwargs = {**current_data(self), **customer_data(self)}
        print(kwargs['current_user'])
        return super().get_context_data(**kwargs)


class RegisterCustomerView(CreateView):
    model = User
    template_name = 'auth_reg/register_customer_page.html'
    form_class = RegisterCustomerForm
    success_url = reverse_lazy('dashboard_customer_page')
    success_msg = W_MESSAGE_CREATE_USER

    def get_context_data(self, **kwargs):
        kwargs = {**current_data(self), **customer_data(self)}
        current_user = kwargs['current_user']
        # current_customer = kwargs['current_customer']
        if kwargs['current_customer']:
            kwargs['logged'] = True
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        # Проверяем, что форма валидна
        if not form.is_valid():
            print("Форма невалидна")
            print(form.errors)  # Логируем ошибки формы
            return self.form_invalid(form)
        self.object = form.save(commit=False)
        form_valid = super().form_valid(form)
        username = form.cleaned_data["email"]
        password = form.cleaned_data["password"]
        try:
            customers_group = Group.objects.get(name='Customers')
        except ObjectDoesNotExist:
            Group.objects.create(name='Customers')
            customers_group = Group.objects.get(name='Customers')
        self.object.groups.add(customers_group)
        self.object.is_active = True
        if self.object.email:
            self.object.slug = str(self.object.email).replace('.', '-').replace('@', '-a-')
            self.object.username = self.object.email
        # Сохранение пользователя
        try:
            self.object.save()  # Попробуем сохранить пользователя
        except Exception as e:
            # print(f"Ошибка при сохранении пользователя: {e}")
            form.add_error(None, "Error saving user")
            return self.form_invalid(form)
        aut_user = authenticate(username=username, password=password)
        # Проверка успешности аутентификации
        if aut_user is not None:
            login(self.request, aut_user)
        else:
            form.add_error(None, "Authentication failed. Please check your credentials.")
            return self.form_invalid(form)
        return form_valid


class RegisterStationView(CreateView):
    model = User
    template_name = 'auth_reg/register_station_page.html'
    form_class = RegisterStationForm
    success_url = reverse_lazy('dashboard_station_page')
    success_msg = W_MESSAGE_CREATE_USER

    def get_context_data(self, **kwargs):
        kwargs = current_data(self)
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        form_valid = super().form_valid(form)
        username = form.cleaned_data["email"]
        password = form.cleaned_data["password"]
        email = form.cleaned_data["email"]
        try:
            stations_group = Group.objects.get(name='Stations')
        except ObjectDoesNotExist:
            Group.objects.create(name='Stations')
            stations_group = Group.objects.get(name='Stations')
        self.object.groups.add(stations_group)
        self.object.is_active = True
        if self.object.email:
            self.object.slug = str(self.object.email).replace('.', '-').replace('@', '-a-')
            self.object.username = self.object.email
        self.object.save()
        aut_user = authenticate(username=username, password=password)
        login(self.request, aut_user)
        return form_valid


class UserLoginView(LoginView):
    template_name = 'auth_reg/login.html'
    form_class = AuthUserForm

    def get_context_data(self, **kwargs):
        kwargs = current_data(self)
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        user = self.request.user
        if user.groups.filter(name="Stations").exists():
            return reverse('dashboard_station_page')
        elif user.groups.filter(name="Customers").exists():
            return reverse('dashboard_customer_page')
        else:
            return reverse_lazy('start_page')


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('start_page')


class UserPasswordResetView(PasswordResetView):
    form_class = PassResetForm
    email_template_name = 'auth_reg/password_reset_email.html'
    template_name = 'auth_reg/password_reset_form.html'

    def get_context_data(self, **kwargs):
        kwargs = reset_password_words(self)
        return super().get_context_data(**kwargs)


class UserPasswordResetDone(PasswordResetDoneView):
    template_name = 'auth_reg/password_reset_done.html'
    title = ('Password reset sent')


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'auth_reg/password_reset_confirm.html'

    def get_context_data(self, **kwargs):
        kwargs = reset_password_words(self)
        return super().get_context_data(**kwargs)


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'auth_reg/password_reset_complete.html'
    title = ('Password reset complete')

    def get_context_data(self, **kwargs):
        kwargs = reset_password_words(self)
        return super().get_context_data(**kwargs)


class DashboardCustomerView(LoginRequiredMixin, ListView):
    """To see cars and orders for customer"""
    model = Customer
    context_object_name = 'get_customer'
    template_name = 'customer/dashboard_cs.html'

    def get_context_data(self, **kwargs):
        kwargs = {**current_data(self), **customer_data(self)}

        return super().get_context_data(**kwargs)


class DetailCustomerView(LoginRequiredMixin, DetailView, CustomSuccessMessageMixin):
    """Info about a customer"""
    model = Customer
    template_name = 'customer/customer.html'
    context_object_name = 'get_customer'

    def get_context_data(self, **kwargs):
        kwargs = {**current_data(self), **customer_data(self)}
        current_user = self.object
        # kwargs['list_car'] = Car.objects.filter(Q(author=current_user) & Q(deleted=False))
        kwargs['customer_url'] = True
        return super().get_context_data(**kwargs)

account/templates/auth_reg/forgot.html
<!DOCTYPE html>
<html lang="en-gb">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <meta name="author" content="" />


    <title>Forgot | Eleven Admin Template</title>
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:900|Anonymous+Pro:400,700|Arimo:400,700"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>
    <svg width="24" height="24" viewBox="0 0 24 24" style="display:none">
      <g
        id="logo-icon"
        stroke="currentColor"
        stroke-width="1"
        stroke-linecap="round"
        stroke-linejoin="round"
        fill="none"
        fill-rule="evenodd"
      >
        <path
          d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"
        ></path>
      </g>
    </svg>

    <div class="page">
      <div class="position-relative d-flex flex-row flex-fill page-wrapper">
        <div
          class="position-relative d-flex flex-column flex-fill page-content"
          style="min-width:0"
        >
          <div
            class="d-flex flex-column justify-content-center align-items-center px-3 bg-white min-vh-100"
          >
            <div class="w-100 auth-card">
              <div class="card shadow-none">
                <div class="card-body">
                  <div class="text-center mb-5">
                    <svg width="24" height="24" class="d-block m-auto">
                      <use xlink:href="#logo-icon"></use>
                    </svg>
                    <h4 class="mb-0 mt-3">Recover your password</h4>
                    <p class="text-muted">
                      Enter your email and we'll send you instructions on how to
                      reset your password.
                    </p>
                  </div>
                  <form class="">
                    <div class="mb-4 form-group">
                      <label for="email" class="">Email</label>
                      <input
                        name="email"
                        id="email"
                        placeholder="Email address"
                        type="email"
                        class="form-control"
                      />
                    </div>
                    <button class="mb-3 btn btn-primary btn-lg btn-block">
                      Reset password
                    </button>
                    <div class="text-center">
                      <small class="text-muted text-center"
                        ><span>Don't have an account yet?</span>
                        <a href="signup.html">Create one now!</a></small
                      >
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="vendor/jquery-3.4.1.slim.min.js"></script>
    <script src="vendor/bootstrap.bundle.min.js"></script>
    <script src="vendor/lottie.js"></script>
  </body>
</html>

account/templates/auth_reg/login.html
{% extends 'start_page.html' %}
{% load static %}


  {% block content %}


    <div class="page">
      <div class="position-relative d-flex flex-row flex-fill page-wrapper">
        <div
          class="position-relative d-flex flex-column flex-fill page-content"
          style="min-width:0">
          <div
            class="d-flex flex-column justify-content-center align-items-center px-3 bg-white min-vh-100">

            {% if messages %}
            <div class="alert alert-success">
              {% for m in messages %}
              {{m}}
              {% endfor %}
            </div>
            {% endif %}

            <div class="w-100 auth-card">
              <div class="shadow p-1 mb-5 bg-white rounded-10">
                <div class="card-body">
                  <div class="text-center mb-3">
                    <p class="mb-0 mt-3">please log in</p>
                    <p class="text-muted">to continue using your account</p>
                  </div>
                  <form class="" id="add_form" method="post">
                      {% csrf_token %}
                    <div class="mb-4 form-group">
                      <label for="id_username" class="">Your email</label>
                        {{form.username}}
                        {% if form.errors %}
                        <p>Your username and password didn't match. Please try again.</p>
                        {% endif %}
                    </div>
                    <div class="mb-4 form-group">
                      <label for="id_password" class="d-flex">
                        <span class="mr-auto">Password</span>
                      </label>
                        {{form.password}}
                    </div>
                      <div class="row">
                          <div class="col-12">
                              <button style="width:100%" form="add_form" type="submit"
                                      class="mb-3 btn btn-primary btn-lg btn-block">
                                  Sign in
                                </button>
                          </div>
                          <div class="col-12">
                              <a style="width:100%" href="{% url 'password_reset' %}"
                                 class="mb-3 btn btn-secondary btn-lg btn-block">
                                  Forgot password?
                                </a>
                          </div>
                      </div>

                    <div class="text-center">
                      <div class="text-muted text-small text-center">
                        <span>Don't have an account yet?</span><br>
                        <a href="{% url 'register_customer_page' %}">Create one now!</a>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

account/templates/auth_reg/password_reset_complete.html
{% extends 'start_page.html' %}
{% load static %}


  {% block content %}


    <div class="page">
      <div class="position-relative d-flex flex-row flex-fill page-wrapper">
        <div
          class="position-relative d-flex flex-column flex-fill page-content"
          style="min-width:0">
          <div
            class="d-flex flex-column justify-content-center align-items-center px-3 bg-white min-vh-100">


            <div class="w-100 auth-card">
              <div class="shadow p-1 mb-5 bg-white rounded-10">
                <div class="card-body">
                  <div class="text-center mb-3">

                    <p class="mb-0 mt-3">{{w_pas_success}}</p>
                  </div>


                      <div class="row">
                          <div class="col-12">
                              <a href="{% url 'login_page' %}" class="w-100 mb-3 btn btn-primary btn-lg btn-block">
                                  {{w_login_button}}
                                </a>
                          </div>
                      </div>


                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

account/templates/auth_reg/password_reset_done.html
{% extends "start_page.html" %}
{% block content %}
    <div class="page">
      <div class="position-relative d-flex flex-row flex-fill page-wrapper">
        <div
          class="position-relative d-flex flex-column flex-fill page-content"
          style="min-width:0">
          <div
            class="d-flex flex-column justify-content-center align-items-center px-3 bg-white min-vh-100">
            <div class="w-100 reset-pass-card">
              <div class="card shadow-none">
                <div class="card-body">
                  <div class="text-center mb-5">
                    <p style="font-size:20px" class="mb-0 mt-3">
                    We've emailed you instructions for setting your password. If they haven't arrived
                    in a few minutes, check your spam folder.</p>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

account/templates/auth_reg/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

{% autoescape off %}


<h3>
    Hi {{ user.get_username }},
</h3>

To initiate the password reset process for your account on {{ domain }},
click the link below:
<br><br>
<a href="{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}">Reset password</a>
<br><br>
If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

account/templates/auth_reg/register_customer_page.html
{% extends 'start_page.html' %}
{% block page_title %}Registration{% endblock %}
{% block style %}
{% endblock style %}

{% block content %}

<div class="page-inner bg-light cs-register-page">
    <div class="row justify-content-center">
        <div class="col-xl-6 col-12">

            <div class="shadow p-1 mt-5 mb-5 bg-white rounded-10">
                <div class=" card">

                    <div class="card-header">
                        <h1 class="">{{w_registration}}</h1>
                        <b style="font-size:18px;">{{w_as_customer}}</b>
                    </div>

                    <div class="card-body">
                        <form id="add_form" method="post">
                        {% csrf_token %}
                            <div class="form-group register-form">
                                <div class="row mt-2">
                                    <div class="col-md-6">
                                    {{ form.titul.label_tag }}
                                    {{ form.titul }}
                                    {% if form.titul.errors %}
                                    {{ form.titul.errors }}
                                    {% endif %}
                                    </div>
                                    <div class="col-md-6">
                                    {{ form.first_name.label_tag }}
                                    {{ form.first_name }}
                                    {% if form.first_name.errors %}
                                    {{ form.first_name.errors }}
                                    {% endif %}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                    {{ form.last_name.label_tag }}
                                    {{ form.last_name }}
                                    {% if form.last_name.errors %}
                                    {{ form.last_name.errors }}
                                    {% endif %}
                                    </div>
                                    <div class="col-md-6">
                                    {{ form.email.label_tag }}
                                    {{ form.email }}
                                    {% if form.email.errors %}
                                    {{ form.email.errors }}
                                    {% endif %}
                                    </div>
                                </div>

                                <div class="row mt-2">
                                    <div class="col-md-6">
                                    {{ form.city.label_tag }}
                                    {{ form.city }}
                                    {% if form.city.errors %}
                                    {{ form.city.errors }}
                                    {% endif %}
                                    </div>
                                    <div class="col-md-6">
                                    {{ form.street.label_tag }}
                                    {{ form.street }}
                                    {% if form.street.errors %}
                                    {{ form.street.errors }}
                                    {% endif %}
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <div class="col-md-6">
                                    {{ form.phone.label_tag }}
                                    {{ form.phone }}
                                    {% if form.phone.errors %}
                                    {{ form.phone.errors }}
                                    {% endif %}
                                    </div>
                                    <div class="col-md-6">
                                    {{ form.address_code.label_tag }}
                                    {{ form.address_code }}
                                    {% if form.address_code.errors %}
                                    {{ form.address_code.errors }}
                                    {% endif %}
                                    </div>
                                </div>

                                <div class="row mt-2">
                                    <div class="col-md-6">
                                    {{ form.password.label_tag }}
                                    {{ form.password }}
                                    {% if form.password.errors %}
                                    {{ form.password.errors }}
                                    {% endif %}
                                    </div>
                                    <div class="col-md-6">
                                        <label for="id_password_2">Confirm password:</label>
                                        <input id="password_2" class="form-control" type="password" name="password_2"
                                               required="true">
                                        <div id="msg"></div>
                                    </div>
                                </div>
                            </div>

                        <div class="row mt-3">
                            <div class="col-6">
                                <div class="form-check form-check-inline ml-2">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" required="true">
                                  I agree with terms and conditions</label>
                                </div>
                            </div>
                            <div class="col-6 text-end">
                                {% if logged %}
                                <button form="no_form" type="button" class="btn btn-secondary">You are already logged</button>
                                {% else %}
                                <button form="add_form" type="submit" class="btn btn-secondary">Register</button>
                                {% endif %}
                            </div>
                        </div>
                    </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script>

    $(document).ready(function(){
        $("#id_titul option[value='']").text("optional");
        $("#id_password").attr('type', 'password');
        $("#password_2").keyup(function(){
             if ($("#id_password").val() != $("#password_2").val()) {
                 $("#msg").html("Password do not match").css("color","red");
             }else{
                 $("#msg").html("Password matched").css("color","green");
             }
        });
    });
</script>

{% endblock %}